name: ezEditsClone
version: 1.0.0
main: com.ezedits.clone.EzEditsPlugin
api-version: '1.21'
depend: [WorldEdit]

commands:
  ezpalette:
    description: Zarządzanie paletami bloków
    permission: ezedits.admin
    aliases: [ezp]
  eznoise:
    description: Generowanie struktur szumu
    permission: ezedits.admin
  ezspline:
    description: Tworzenie linii i łuków
    permission: ezedits.admin
  eztexture:
    description: Teksturowanie światłem, wysokością i widokiem gracza
    permission: ezedits.admin
    aliases: [ezt]

permissions:
  ezedits.admin:
    default: op
